name: Check Tests in pull requests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: Linter
          command: npm run lint
        - name: Build
          command: npm run build
        - name: Unit Tests
          command: npm test
        - name: e2e tests
          command: |
            docker-compose --project-directory ./test -f ./test/e2e.docker-compose.yml pull
            docker-compose --project-directory ./test -f ./test/e2e.docker-compose.yml build
            DEBUG=testcontainers:containers npm run test:e2e

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: 
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}